#spring.application.name=configserver

#config server port
#server.port=8888

#Link Configserver with GITLab Account
#spring.cloud.config.server.git.uri=https://gitlab.com/Ramachandrarao24/service-marketplace-microservices.git
#spring.cloud.config.server.git.uri=https://gitlab.com/Ramachandrarao24/service-marketplace-microservices.git
#spring.cloud.config.server.git.skip-ssl-validation=true
#spring.cloud.config.server.git.clone-on-start=true

#Link with Eureka server
eureka.client.service-url.defaultzone=http://localhost:8761/eureka

spring.application.name=configserver

server.port=8888

spring.cloud.config.server.git.uri=https://gitlab.com/Ramachandrarao24/service-marketplace-microservices.git

spring.cloud.config.server.git.clone-on-start=true

spring.cloud.config.server.git.skip-ssl-validation=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
